@startuml PFE_use_case
actor "Développeur" as Dev
actor "Gestionnaire de Projet" as PM
actor "Client" as Client

rectangle {
  Dev --> (Visualiser Historique des Modifications)
  PM --> (Visualiser Fichiers les Plus Modifiés)
  Client --> (Visualiser Changements de la Version)

  (Visualiser Historique des Modifications) .> (Charger Répertoire GitHub) : include
  (Visualiser Historique des Modifications) .> (Sélectionner Fichier) : include

  (Visualiser Fichiers les Plus Modifiés) .> (Charger Répertoire GitHub) : include

  (Visualiser Changements de la Version) .> (Charger Répertoire GitHub) : include
  (Visualiser Changements de la Version) .> (Sélectionner Version) : include
}
@enduml
